language: android
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - android-27
    - extra-android-m2repository
    - extra-android-support

install:
  - echo y | sdkmanager 'ndk-bundle;15.2.4203891'
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - echo y | sdkmanager 'lldb;3.0'

before_install:
  - chmod +x ./VirtualApp/gradlew

script:
  - cd VirtualApp
  - ./gradlew assembleRelease
